#ifndef layerh
#define layerh

#define ulli unsigned long long int

#include"vector.h"
#include"activationfunctions.h"

#define ulli unsigned long long int

typedef struct layer layer;
struct layer
{
	ulli layer_width;	// number of outputs generated by the layer
	
	double* output;
	double* activated_output;
	
	double* output_gradient;
	
	double* bias;
	double* bias_change;
	
	activation_type act_type;
};

void init_layer(layer* l,ulli layer_width,double weight_range,activation_type act_type);
void delete_layer(layer* l);
void activate_layer(layer* l);
void deactivate_layer(layer* l);
void print_layer(layer* l);
void set_bias_layer(layer* l);
void update_bias_layer(layer* l);

#endif
